### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-experian#29]
![image](https://cloud.githubusercontent.com/assets/569/10205645/0b0c38d4-6788-11e5-9cd7-fa570b6dce01.png)

**Comment by alexkwolfe** [comment]
This is still a problem.

```
TypeError: Cannot read property 'length' of undefined
        at Object.request (./leadconduit-experian/lib/zip4_credit_score_lookup.js:19:52)
```

**Comment by ros3bud** [comment]
This is because the key is not in production. Will be updated shortly per @cgrayson.

**Comment by ros3bud** [comment]
Updated per this test lead on production: https://next.leadconduit.com/events/56390561531ff4f03a67dc7e?event_id=56390561531ff4f03a67dc7f.

**Comment by alexkwolfe** [comment]
It's probably worth checking that the key is set in the `validate()` function.

**Comment by ros3bud** [comment]
It is not. I can close this up and add a new issue for that.
